# Generated by Django 3.1.5 on 2021-04-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20210414_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=250, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
